# Линейная алгебра в Python
* [NumPy](#NumPy)
* [NumPy array](#NumPy-array)
* [Создание массивов](#Создание-массивов)
* [Сравнение скорости работы](#Сравнение-скорости-работы)
* [Поэлементные операции](#Поэлементные-операции)
* [Задача - индексирование](#Задача---индексирование)
* [Задача - Шкалирование](#Задача---Шкалирование)
* [Задача - Линейная-регрессия](#Задача---Линейная-регрессия)
* [Ссылки](#Ссылки)

# NumPy

<img src="http://www.numpy.org/_static/numpy_logo.png" width="200">

**NumPy** — это библиотека с открытым исходным кодом для языка программирования Python.

* Поддержка многомерных массивов (включая матрицы).
* Поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.

# NumPy array
<img src="http://www.extremetech.com/media/images/1030.gif?thumb=y" width="200">

**`ndarray`** - класс однородных многомерных массивов.  
В `numpy` доступно большое количество методов и функций по работе с массивами.

## Создание массивов

In [ ]:
import numpy as np

In [ ]:
np.array([1, 2, 4])

In [ ]:
np.arange(10)

Полезные функции, создающие массив:
* [`array`](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.array.html#numpy.array)
* [`linspace`](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.linspace.html#numpy.linspace)
* [`arange`](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.arange.html#numpy.arange)
* [Подробнее](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html#functions-and-methods-overview)

# Сравнение скорости работы

In [ ]:
for d in [4, 7]:
    print('dimension: ', d)
    lst = list(range(10**d))
    arr = np.arange(10**d)
    %time sum(lst)
    %time np.sum(arr)
    print('-'*20)

# Поэлементные операции

In [ ]:
arr1 = np.arange(10)
arr2 = np.arange(100, 110)

# Задача - индексирование
Реализуйте функцию, принимающую на вход матрицу X и два массива i и j одинаковой длины и возвращающую вектор np.array, состоящий из последовательности элементов [X[i[0], j[0]], X[i[1], j[1]], ..., X[i[N-1], j[N-1]]].

In [ ]:
def construct_array(X, i, j):
    '''
    >>> X = np.array([[0, 1, 2], [3, 4, 5]])
    >>> i = np.array([0, 0, 0, 1, 1, 1])
    >>> j = np.array([0, 1, 2, 2, 1, 0])
    >>> construct_array(X, i, j)
    array([0, 1, 2, 5, 4, 3])
    '''
    pass

# Задача - Шкалирование
Написать функцию, которая получает на вход матрицу и масштабирует каждый её столбец, а именно вычитает из столбца его среднее значение и делит столбец на стандартное отклонение. 

In [ ]:
def scale(X):
    '''Scaling the matrix
    
    >>> X = np.random.randn(10, 3)
    >>> X_sc = scale(X)
    >>> X_sc.std(axis=0)
    array([ 1.,  1.,  1.])
    >>> X_sc.mean(axis=0)
    array([ 0.,  0.,  0.])
    '''
    pass

# Задача - Линейная регрессия


Путь $X$ - матрица признаков, а $y$ - целевая переменная. Функция потерь $Q = |Xw - y|^2 + C|w|^2$.

Решение $\hat{w} = (X^TX + СI)^{-1}X^Ty$.

Реализуете класс - линейная регрессия.
[wiki](http://www.machinelearning.ru/wiki/index.php?title=Гребневая_регрессия)

In [ ]:
class LinearReg():

    def __init__(self, C=1):
        pass

    def fit(self, X, y):
        pass
        return self

    def predict(self, X):
        pass

Полезные функции:
* [`.dot`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) - матричное произведение
* [`np.linalg.inv`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html) - обращение матрицы
* [`.T`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html) - транспонирование
* [`np.eye`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html) - создание единичной матрицы

In [ ]:
np.random.seed(42)
X = np.random.rand(10, 3)
w = np.array([1, -1, 10])
y = X.dot(w)

Для тестирование сравните с [`LinearRegression`](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html) и [`Ridge`](http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Ridge.html) из scikit learn.

# Ссылки

* [wiki](https://ru.wikipedia.org/wiki/NumPy)
* [Официальный сайт NumPy](http://www.numpy.org)
* [NumPy tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)
* [Пост про numpy с datacamp вместе с интерактивными вставками](https://www.datacamp.com/community/tutorials/python-numpy-tutorial#gs.190Kw0g)
* [NumpyTipsAndTricks](http://arogozhnikov.github.io/2015/09/29/NumpyTipsAndTricks1.html) - продвинутые примеры работы с numpy